version = 1

test_patterns = ["__tests__/**"]

exclude_patterns = ["build/**", "typedoc-docs/**", "testdata/**", "templates/**"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true