name: feature

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'feature/*'
      - 'hotfix/*'

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm audit fix
          npm test
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_URL: ${{ secrets.FIGMA_URL }}
          IS_CI: true
        run: |
          npm install -g
          npm run figmagic
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_URL: ${{ secrets.FIGMA_URL }}
        run: |
          \[ -d .figmagic \]
          \[ -f .figmagic/figma.json \]
        env:
          CI: true

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest']
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        id: node
      - run: |
          npm ci --ignore-scripts
          npm audit fix
      # run: npm test
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_URL: ${{ secrets.FIGMA_URL }}
          IS_CI: true
      - run: |
          npm install -g
          npm run figmagic
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_URL: ${{ secrets.FIGMA_URL }}
      - run: |
          Test-Path .figmagic
          Test-Path .figmagic/figma.json -PathType leaf
        env:
          CI: true
